### ISSUE TITLE
Provides option to manually set location on location data popup error

### ISSUE THREAD

**Issue by rc4dayyan** [novalagung/muslimboardindo#27]
Salam @novalagung,
I'm impressed with this extension and would be grateful if be allowed to contribute

When I run this extension for the first time then a popup appears where it fails to detect the user's position, what if I try to add a button (choose manual location) to the popup, so when the user clicks the button it should open a manual location setup popup?

Thanks

**Comment by novalagung** [comment]
hi @rc4dayyan, thank you for informing the issue.

really appreciate the suggestion, thank you. I think it's good, but there is one problem:

starting around a month ago the extension supports multiple languages, and based on the metrics I can confirm that some of our users are located outside of Indonesia. and that is where the problem lies. the manual location popup only shows the Indonesian cities (exclusively). the solution works for Indonesian people but it will cause additional confusion for non-Indonesian users because only Indonesian cities are available there.

**Comment by rc4dayyan** [comment]
ah yes, I got your point @novalagung
