### ISSUE TITLE
Slightly Incorrect Prayer Times

### ISSUE THREAD

**Issue by barraIhsan** [novalagung/muslimboardindo#84]
The prayer times provided in the extension is kinda incorrect. As you can see here, Muslim Pro shows this in the capital city of Indonesia, Jakarta.
Why Muslim Pro you asked? Well, because I can't find a single app which is more accurate than Muslim Pro, I even cross-checked it into many masjids, and it's correct (sometimes it's 1 or 2 minutes different)
![image](https://github.com/novalagung/muslimboard/assets/57800056/2eab91e7-fe4d-419c-9f3e-b56b774536d2)

And here are the prayer times provided by the extension (set manually and choose Jakarta)
![image](https://github.com/novalagung/muslimboard/assets/57800056/3ca66392-d720-4ed1-9e77-03c5fa4602ef)

Either way, syukron for this beautiful extension

**Comment by novalagung** [comment]
@barraIhsan we are using a combination of openstreetmap (for geolocation findings) and aladhan API (for calculating prayer times). the result is ok, but it will never be as accurate as the one from Kemenag.

Our problem is actually the API limitation. If we can get a better source that can provide more accurate data, we will use it. but as of now, we can't find anything better.

I contacted the Kemenag to get their public API access for prayer times, but no luck. 

I'm closing this issue because I've received quite an amount of similar feedback already. I appreciate the report though.

Kindly let me know if you have some info about a better data source provider that can generate accurate prayer times.
